;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
ll=ls -lh --show-control-chars -F --color $*  
la=ls -a --show-control-chars -F --color $*  
home=cd /d c:\Users\mmalolepszy\  
projects=cd /d c:\Projects\  
dn=dotnet $*  
gs=git status -sb $*  
p=ping 8.8.8.8  
gl=git log --oneline --branches --remotes --tags --graph --decorate -n15 $*  
gla=git log --oneline --branches --remotes --tags --graph --decorate $*  
